### ISSUE TITLE
LRBV airport missing

### ISSUE THREAD

**Issue by tgpetrica** [vatis-project/navdata#4]
Hello, 

LRBV Brasov International Airport is a new airport opened last month, by AIRAC 2306. 

Could you add the airport in the airports file?

```yaml
- ID: LRBV
  Name: BRASOV GHIMBAV INTERNATIONAL AIRPORT
  Lat: 45.70611
  Lon: 25.52333
```

On behalf of the VATSIM Romania OPS team, 
Thank you
